name: Secret Usage with API Test

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Prüfen, ob Secret existiert
        run: |
          if [[ -z "${{ secrets.API_KEY }}" ]]; then
            echo "Secret MY_SECRET_API_KEY ist nicht gesetzt!"
            exit 1
          else
            echo "Secret wurde erfolgreich geladen."
          fi

      - name: API-Test mit Secret
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/posts/1'  # Dummy-API zum Testen
          method: 'GET'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.MY_SECRET_API_KEY }}"}'

      - name: Erfolgreich abgeschlossen
        run: echo "Workflow erfolgreich ausgeführt!"
