name: Secret Usage Demo

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Geheimen API-Schlüssel verwenden
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [[ -z "$API_KEY" ]]; then
            echo "Secret ist nicht gesetzt!"
            exit 1
          else
            echo "Secret wurde erfolgreich geladen."
          fi

      - name: Dummy API-Aufruf
        run: |
          echo "Sende API-Anfrage mit geheimer API-Key (wird nicht geloggt)"
